### ISSUE TITLE
2.Fáza : Návrh

### ISSUE THREAD

**Issue by Matejj2002** [TIS2024-FMFI/profilometry#12]
Vytvorenie návrhu v tomto poradí:
- [x] podrobná špecifikácia vonkajších interfejsov
- [x] podrobný dátový model perzistentných údajov
- [x] návrh používateľského rozhrania
- [ ] Zrozumiteľný a jednoznačný návrh implementácie
- [x] Plán implementácie

**Následné schválenie návrhu cvičiacím**

**Deadline: 12.11**

**Comment by viki-terebova** [comment]
Bolo by super zacat to riesit na spolocnom stretnuti v pondelok 16:00, dovtedy by si kazdy mohol pozriet co sa da pouzit

**Comment by KSFMFI-LPI** [comment]
treba dokoncit UML diagramy a ich popisat

**Comment by KSFMFI-LPI** [comment]
este je potrebne dotiahnut GUI obrazky a popis

**Comment by viki-terebova** [comment]
https://liveuniba-my.sharepoint.com/:w:/r/personal/gornal1_uniba_sk/_layouts/15/Doc.aspx?sourcedoc=%7B8A0B10B5-27CB-4CFB-9380-F2051E5E91A6%7D&file=N%C3%A1vrh%20-%20dokument%C3%A1cia.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1731779479874&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=d0bbf179-effc-4f1f-8748-91ee69367de4&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=bd44f97e-b550-4192-9dbf-7ec93f52d0c0
