### ISSUE TITLE
upravit katalog poziadaviek na zaklade pripomienok od cviciaceho

### ISSUE THREAD

**Issue by KSFMFI-LPI** [TIS2024-FMFI/profilometry#19]

**Comment by viki-terebova** [comment]
Skontrolovany katalog, poprehadzovanie poradia poziadaviek, vymazanie duplicitov a sprehladnenie poziadaviek.

**Comment by KSFMFI-LPI** [comment]
zjednotenie formatu katalogu

**Comment by KSFMFI-LPI** [comment]
doupravovany katalog
