### ISSUE TITLE
vytvorit Katalog poziadaviek

### ISSUE THREAD

**Issue by KSFMFI-LPI** [TIS2024-FMFI/profilometry#2]

**Comment by Matejj2002** [comment]
Kostra Katalógu požiadaviek urobená

**Comment by Matejj2002** [comment]
1. Kapitola urobená
2. Kapitola urobená

**Comment by viki-terebova** [comment]
Doplnenie 3. kapitoly

**Comment by KSFMFI-LPI** [comment]
doplneny slovnik pojmov

**Comment by KSFMFI-LPI** [comment]
upravena 2 a 3 kapitola

**Comment by pavelpetrovic** [comment]
najskor cviciacemu, az ked bude suhlasit, potom zadavatelovi.
