### ISSUE TITLE
Hľadanie čiary

### ISSUE THREAD

**Issue by Matejj2002** [TIS2024-FMFI/profilometry#24]
Zdroje pre nájdenie čiar: https://www.youtube.com/watch?v=8M5Ej1NOjy4 | https://www.youtube.com/watch?v=_Z2lU--poFQ

Potreba mať nejaký threshold, ktorý určí rozpyl, v ktorom sa čiara považuje ešte že je tá istá
- [x] Algoritmus na nájdenie všetkých čiar
- [x] Houghová transformácia pre nájdenie čiar
- [x] 1. Algoritmus nájde všetky čiary
- [x] 2.1. Algoritmus spojí čiary ktoré sú blízko seba do jednej - prvej ktorú nájde
- [x] 2.2 Algoritmus spojí čiary ktoré sú blízko seba, ale hlavnú čiaru určí na základe priemeru y-ových hodnôt 
- [x] 3. Algoritmus pomocou najsvetlejsieho bodu scanu
- [x] 3.1 Referencna ciara a bod po bode objekt

**Comment by KSFMFI-LPI** [comment]
na zaklade preriesenia situacie progresu na stretnuti 5:

- [ ]  vytvorit novy dokument - na celkovu dokumentaciu
- [ ] poslat Viki pouzivane kniznice pri detekcii ciar
- [ ] zistit ako expozicia suvisi s nedokonalostou najdeneho algoritmu
- [ ] zistit moznosti ako  vylepsit algoritmus , aby boli osetrene nespravne pripady
- [ ] pripadne prist s inym riesenim tohto problemu "tretej ciary"
- [ ]  dalsia moznost : upravit implementaciu tak aby si pouzivatel vedel odsuhlasit sken - ak sa rozhodneme ist touto cestou , tak ju treba preverit a pripadne implementovat
