### ISSUE TITLE
spojenie citania kamery (Lukas) so spracovanim skenu (Matej)

### ISSUE THREAD

**Issue by viki-terebova** [TIS2024-FMFI/profilometry#36]

**Comment by Matejj2002** [comment]
Po nasnímaní skenov v časti Scan Images, potrebujeme uložiť cestu k tomuto projektu, aby sa potom po prekliknutí na zobrazovanie skenov používateľ nepotreboval hľadať tento projekt, ale automaticky sa mu už otvorí.
